In [39]:
import pandas as pd

In [40]:
pd.set_option('display.max_rows', None)

In [41]:
df8 = pd.read_csv('./8.상주인구.csv', encoding='cp949')

C:\Users\82103\AppData\Local\Temp\ipykernel_5348\417379837.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df8 = pd.read_csv('./8.상주인구.csv', encoding='cp949')

In [42]:
df1 = pd.read_csv('./1.상권영역(정보).csv', encoding='cp949')

In [43]:
df1.head(5).T

                   0         1             2             3         4
기준_년월_코드      201810    201810        201810        201810    201810
상권_구분_코드           A         A             D             D         D
상권_구분_코드_명      골목상권      골목상권          발달상권          발달상권      발달상권
상권_코드        1000275   1000276       1001045       1001046   1001047
상권_코드_명       보문로26길    보문로31길  동작구 총신대입구역_1  서울 관악구 신림역_4   뱅뱅사거리_1
엑스좌표_값        201886    201385        198304        193828    202960
와이좌표_값        454183    454290        442948        443001    443242
시군구_코드         11290     11290         11590         11620     11680
행정동_코드      11290600  11290555      11590630      11620695  11680655
형태정보             NaN       NaN           NaN           NaN       NaN

In [44]:
df2 = pd.read_csv('./2.상권변화(자치구).csv', encoding='cp949')

In [45]:
df2.head(5).T

                    0      1      2      3      4
기준_년_코드          2021   2021   2021   2021   2021
기준_분기_코드            3      3      3      3      3
시군구_코드          11740  11710  11680  11650  11620
시군구_코드_명          강동구    송파구    강남구    서초구    관악구
상권_변화_지표           LL     LL     LL     HH     LL
상권_변화_지표_명       다이나믹   다이나믹   다이나믹     정체   다이나믹
운영_영업_개월_평균       111    116    109    127    114
폐업_영업_개월_평균        52     55     51     55     53
서울_운영_영업_개월_평균    117    117    117    117    117
서울_폐업_영업_개월_평균     55     55     55     55     55

In [46]:
df3 = pd.read_csv('./3.상권변화(행정동).csv', encoding='cp949')

In [47]:
df3.head(5).T

                       0         1         2         3         4
기준_년_코드             2021      2021      2021      2021      2021
기준_분기_코드               3         3         3         3         3
행정동_코드          11740700  11740690  11740685  11740660  11740650
행정동_코드_명            둔촌2동      둔촌1동        길동      성내3동      성내2동
상권_변화_지표              HL        HH        LL        HL        LL
상권_변화_지표_명          상권축소        정체      다이나믹      상권축소      다이나믹
운영_영업_개월_평균          119       170       110       119       116
폐업_영업_개월_평균           52        72        49        48        48
서울_운영_영업_개월_평균       117       117       117       117       117
서울_폐업_영업_개월_평균        55        55        55        55        55

In [48]:
df5 = pd.read_csv('./5.소득소비(상권배후지).csv', encoding='cp949')

In [49]:
df5.head(5).T

                       0            1           2           3           4
기준 년 코드             2021         2021        2021        2021        2021
기준_분기_코드               1            1           1           1           1
상권_구분_코드               A            A           A           A           A
상권_구분_코드_명          골목상권         골목상권        골목상권        골목상권        골목상권
상권_코드            1000193      1000298     1000297     1000296     1000295
상권_코드_명           왕산로43길       정릉로27길      정릉로26길      장위로50길       장월로1길
월_평균_소득_금액       2729716      3355209     3338064     2416795     2956757
소득_구간_코드               6            7           7           5           6
지출_총금액        7501923026  11842475922  6179246740  5235197988  4803914725
식료품_지출_총금액    2151712515   3099929654  1683952466  1501033989  1364476852
의류_신발_지출_총금액   888933146   1428912815   733874296   616414129   574723444
생활용품_지출_총금액    553108402    849935987   430168476   374450525   344562961
의료비_지출_총금액    1067767035   1555173516   826003935   756011966   659910597
교통_지출_총금액     1166698759   1968536418   976992453   807825584   734715693
여가_지출_총금액      261418507    440069908   213755800   183610620   163371736
문화_지출_총금액      233074790    348552899   182240005   160542222   152451762
교육_지출_총금액      865027157   1651824332   871685006   621093249   605566880
유흥_지출_총금액      314182715    499540393   260574303   214215704   204134800

In [ ]:
df6 = pd.read_csv('./6.생활인구-1.csv')

In [58]:
df6.head(3)

,기준 년코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드.1,상권_코드_명,총_생활인구_수,남성_생활인구_수,여성_생활인구_수,연령대_10_생활인구_수,연령대_20_생활인구_수,연령대_30_생활인구_수,연령대_40_생활인구_수,연령대_50_생활인구_수,연령대_60_이상_생활인구_수,시간대_1_생활인구_수,시간대_2_생활인구_수,시간대_3_생활인구_수,시간대_4_생활인구_수,시간대_5_생활인구_수,시간대_6_생활인구_수,월요일_생활인구_수,화요일_생활인구_수,수요일_생활인구_수,목요일_생활인구_수,금요일_생활인구_수,토요일_생활인구_수,일요일_생활인구_수,남성연령대_10_월요일시간대_1_생활인구_수,남성연령대_10_월요일시간대_2_생활인구_수,남성연령대_10_월요일시간대_3_생활인구_수,남성연령대_10_월요일시간대_4_생활인구_수,남성연령대_10_월요일시간대_5_생활인구_수,남성연령대_10_월요일시간대_6_생활인구_수,남성연령대_10_화요일시간대_1_생활인구_수,남성연령대_10_화요일시간대_2_생활인구_수,남성연령대_10_화요일시간대_3_생활인구_수,남성연령대_10_화요일시간대_4_생활인구_수,남성연령대_10_화요일시간대_5_생활인구_수,남성연령대_10_화요일시간대_6_생활인구_수,남성연령대_10_수요일시간대_1_생활인구_수,남성연령대_10_수요일시간대_2_생활인구_수,남성연령대_10_수요일시간대_3_생활인구_수,남성연령대_10_수요일시간대_4_생활인구_수,남성연령대_10_수요일시간대_5_생활인구_수,남성연령대_10_수요일시간대_6_생활인구_수,남성연령대_10_목요일시간대_1_생활인구_수,남성연령대_10_목요일시간대_2_생활인구_수,남성연령대_10_목요일시간대_3_생활인구_수,남성연령대_10_목요일시간대_4_생활인구_수,남성연령대_10_목요일시간대_5_생활인구_수,남성연령대_10_목요일시간대_6_생활인구_수,남성연령대_10_금요일시간대_1_생활인구_수,남성연령대_10_금요일시간대_2_생활인구_수,남성연령대_10_금요일시간대_3_생활인구_수,남성연령대_10_금요일시간대_4_생활인구_수,남성연령대_10_금요일시간대_5_생활인구_수,남성연령대_10_금요일시간대_6_생활인구_수,남성연령대_10_토요일시간대_1_생활인구_수,남성연령대_10_토요일시간대_2_생활인구_수,남성연령대_10_토요일시간대_3_생활인구_수,남성연령대_10_토요일시간대_4_생활인구_수,남성연령대_10_토요일시간대_5_생활인구_수,남성연령대_10_토요일시간대_6_생활인구_수,남성연령대_10_일요일시간대_1_생활인구_수,남성연령대_10_일요일시간대_2_생활인구_수,남성연령대_10_일요일시간대_3_생활인구_수,남성연령대_10_일요일시간대_4_생활인구_수,남성연령대_10_일요일시간대_5_생활인구_수,남성연령대_10_일요일시간대_6_생활인구_수,남성연령대_20_월요일시간대_1_생활인구_수,남성연령대_20_월요일시간대_2_생활인구_수,남성연령대_20_월요일시간대_3_생활인구_수,남성연령대_20_월요일시간대_4_생활인구_수,남성연령대_20_월요일시간대_5_생활인구_수,남성연령대_20_월요일시간대_6_생활인구_수,남성연령대_20_화요일시간대_1_생활인구_수,남성연령대_20_화요일시간대_2_생활인구_수,남성연령대_20_화요일시간대_3_생활인구_수,남성연령대_20_화요일시간대_4_생활인구_수,남성연령대_20_화요일시간대_5_생활인구_수,남성연령대_20_화요일시간대_6_생활인구_수,남성연령대_20_수요일시간대_1_생활인구_수,남성연령대_20_수요일시간대_2_생활인구_수,남성연령대_20_수요일시간대_3_생활인구_수,남성연령대_20_수요일시간대_4_생활인구_수,남성연령대_20_수요일시간대_5_생활인구_수,남성연령대_20_수요일시간대_6_생활인구_수,남성연령대_20_목요일시간대_1_생활인구_수,남성연령대_20_목요일시간대_2_생활인구_수,남성연령대_20_목요일시간대_3_생활인구_수,남성연령대_20_목요일시간대_4_생활인구_수,남성연령대_20_목요일시간대_5_생활인구_수,남성연령대_20_목요일시간대_6_생활인구_수,남성연령대_20_금요일시간대_1_생활인구_수,남성연령대_20_금요일시간대_2_생활인구_수,남성연령대_20_금요일시간대_3_생활인구_수,남성연령대_20_금요일시간대_4_생활인구_수,남성연령대_20_금요일시간대_5_생활인구_수,남성연령대_20_금요일시간대_6_생활인구_수,남성연령대_20_토요일시간대_1_생활인구_수,남성연령대_20_토요일시간대_2_생활인구_수,남성연령대_20_토요일시간대_3_생활인구_수,남성연령대_20_토요일시간대_4_생활인구_수,남성연령대_20_토요일시간대_5_생활인구_수,남성연령대_20_토요일시간대_6_생활인구_수,남성연령대_20_일요일시간대_1_생활인구_수,남성연령대_20_일요일시간대_2_생활인구_수,남성연령대_20_일요일시간대_3_생활인구_수,남성연령대_20_일요일시간대_4_생활인구_수,남성연령대_20_일요일시간대_5_생활인구_수,남성연령대_20_일요일시간대_6_생활인구_수,남성연령대_30_월요일시간대_1_생활인구_수,남성연령대_30_월요일시간대_2_생활인구_수,남성연령대_30_월요일시간대_3_생활인구_수,남성연령대_30_월요일시간대_4_생활인구_수,남성연령대_30_월요일시간대_5_생활인구_수,남성연령대_30_월요일시간대_6_생활인구_수,남성연령대_30_화요일시간대_1_생활인구_수,남성연령대_30_화요일시간대_2_생활인구_수,남성연령대_30_화요일시간대_3_생활인구_수,남성연령대_30_화요일시간대_4_생활인구_수,남성연령대_30_화요일시간대_5_생활인구_수,남성연령대_30_화요일시간대_6_생활인구_수,남성연령대_30_수요일시간대_1_생활인구_수,남성연령대_30_수요일시간대_2_생활인구_수,남성연령대_30_수요일시간대_3_생활인구_수,남성연령대_30_수요일시간대_4_생활인구_수,남성연령대_30_수요일시간대_5_생활인구_수,남성연령대_30_수요일시간대_6_생활인구_수,남성연령대_30_목요일시간대_1_생활인구_수,남성연령대_30_목요일시간대_2_생활인구_수,남성연령대_30_목요일시간대_3_생활인구_수,남성연령대_30_목요일시간대_4_생활인구_수,남성연령대_30_목요일시간대_5_생활인구_수,남성연령대_30_목요일시간대_6_생활인구_수,남성연령대_30_금요일시간대_1_생활인구_수,남성연령대_30_금요일시간대_2_생활인구_수,남성연령대_30_금요일시간대_3_생활인구_수,남성연령대_30_금요일시간대_4_생활인구_수,남성연령대_30_금요일시간대_5_생활인구_수,남성연령대_30_금요일시간대_6_생활인구_수,남성연령대_30_토요일시간대_1_생활인구_수,남성연령대_30_토요일시간대_2_생활인구_수,남성연령대_30_토요일시간대_3_생활인구_수,남성연령대_30_토요일시간대_4_생활인구_수,남성연령대_30_토요일시간대_5_생활인구_수,남성연령대_30_토요일시간대_6_생활인구_수,남성연령대_30_일요일시간대_1_생활인구_수,남성연령대_30_일요일시간대_2_생활인구_수,남성연령대_30_일요일시간대_3_생활인구_수,남성연령대_30_일요일시간대_4_생활인구_수,남성연령대_30_일요일시간대_5_생활인구_수,남성연령대_30_일요일시간대_6_생활인구_수,남성연령대_40_월요일시간대_1_생활인구_수,남성연령대_40_월요일시간대_2_생활인구_수,남성연령대_40_월요일시간대_3_생활인구_수,남성연령대_40_월요일시간대_4_생활인구_수,남성연령대_40_월요일시간대_5_생활인구_수,남성연령대_40_월요일시간대_6_생활인구_수,남성연령대_40_화요일시간대_1_생활인구_수,남성연령대_40_화요일시간대_2_생활인구_수,남성연령대_40_화요일시간대_3_생활인구_수,남성연령대_40_화요일시간대_4_생활인구_수,남성연령대_40_화요일시간대_5_생활인구_수,남성연령대_40_화요일시간대_6_생활인구_수,남성연령대_40_수요일시간대_1_생활인구_수,남성연령대_40_수요일시간대_2_생활인구_수,남성연령대_40_수요일시간대_3_생활인구_수,남성연령대_40_수요일시간대_4_생활인구_수,남성연령대_40_수요일시간대_5_생활인구_수,남성연령대_40_수요일시간대_6_생활인구_수,남성연령대_40_목요일시간대_1_생활인구_수,남성연령대_40_목요일시간대_2_생활인구_수,남성연령대_40_목요일시간대_3_생활인구_수,남성연령대_40_목요일시간대_4_생활인구_수,남성연령대_40_목요일시간대_5_생활인구_수,남성연령대_40_목요일시간대_6_생활인구_수,남성연령대_40_금요일시간대_1_생활인구_수,남성연령대_40_금요일시간대_2_생활인구_수,남성연령대_40_금요일시간대_3_생활인구_수,남성연령대_40_금요일시간대_4_생활인구_수,남성연령대_40_금요일시간대_5_생활인구_수,남성연령대_40_금요일시간대_6_생활인구_수,남성연령대_40_토요일시간대_1_생활인구_수,남성연령대_40_토요일시간대_2_생활인구_수,남성연령대_40_토요일시간대_3_생활인구_수,남성연령대_40_토요일시간대_4_생활인구_수,남성연령대_40_토요일시간대_5_생활인구_수,남성연령대_40_토요일시간대_6_생활인구_수,남성연령대_40_일요일시간대_1_생활인구_수,남성연령대_40_일요일시간대_2_생활인구_수,남성연령대_40_일요일시간대_3_생활인구_수,남성연령대_40_일요일시간대_4_생활인구_수,남성연령대_40_일요일시간대_5_생활인구_수,남성연령대_40_일요일시간대_6_생활인구_수,남성연령대_50_월요일시간대_1_생활인구_수,남성연령대_50_월요일시간대_2_생활인구_수,남성연령대_50_월요일시간대_3_생활인구_수,남성연령대_50_월요일시간대_4_생활인구_수,남성연령대_50_월요일시간대_5_생활인구_수,남성연령대_50_월요일시간대_6_생활인구_수,남성연령대_50_화요일시간대_1_생활인구_수,남성연령대_50_화요일시간대_2_생활인구_수,남성연령대_50_화요일시간대_3_생활인구_수,남성연령대_50_화요일시간대_4_생활인구_수,남성연령대_50_화요일시간대_5_생활인구_수,남성연령대_50_화요일시간대_6_생활인구_수,남성연령대_50_수요일시간대_1_생활인구_수,남성연령대_50_수요일시간대_2_생활인구_수,남성연령대_50_수요일시간대_3_생활인구_수,남성연령대_50_수요일시간대_4_생활인구_수,남성연령대_50_수요일시간대_5_생활인구_수,남성연령대_50_수요일시간대_6_생활인구_수,남성연령대_50_목요일시간대_1_생활인구_수,남성연령대_50_목요일시간대_2_생활인구_수,남성연령대_50_목요일시간대_3_생활인구_수,남성연령대_50_목요일시간대_4_생활인구_수,남성연령대_50_목요일시간대_5_생활인구_수,남성연령대_50_목요일시간대_6_생활인구_수,남성연령대_50_금요일시간대_1_생활인구_수,남성연령대_50_금요일시간대_2_생활인구_수,남성연령대_50_금요일시간대_3_생활인구_수,남성연령대_50_금요일시간대_4_생활인구_수,남성연령대_50_금요일시간대_5_생활인구_수,남성연령대_50_금요일시간대_6_생활인구_수,남성연령대_50_토요일시간대_1_생활인구_수,남성연령대_50_토요일시간대_2_생활인구_수,남성연령대_50_토요일시간대_3_생활인구_수,남성연령대_50_토요일시간대_4_생활인구_수,남성연령대_50_토요일시간대_5_생활인구_수,남성연령대_50_토요일시간대_6_생활인구_수,남성연령대_50_일요일시간대_1_생활인구_수,남성연령대_50_일요일시간대_2_생활인구_수,남성연령대_50_일요일시간대_3_생활인구_수,남성연령대_50_일요일시간대_4_생활인구_수,남성연령대_50_일요일시간대_5_생활인구_수,남성연령대_50_일요일시간대_6_생활인구_수,남성연령대_60_이상_월요일시간대_1_생활인구_수,남성연령대_60_이상_월요일시간대_2_생활인구_수,남성연령대_60_이상_월요일시간대_3_생활인구_수,남성연령대_60_이상_월요일시간대_4_생활인구_수,남성연령대_60_이상_월요일시간대_5_생활인구_수,남성연령대_60_이상_월요일시간대_6_생활인구_수,남성연령대_60_이상_화요일시간대_1_생활인구_수,남성연령대_60_이상_화요일시간대_2_생활인구_수,남성연령대_60_이상_화요일시간대_3_생활인구_수,남성연령대_60_이상_화요일시간대_4_생활인구_수,남성연령대_60_이상_화요일시간대_5_생활인구_수,남성연령대_60_이상_화요일시간대_6_생활인구_수,남성연령대_60_이상_수요일시간대_1_생활인구_수,남성연령대_60_이상_수요일시간대_2_생활인구_수,남성연령대_60_이상_수요일시간대_3_생활인구_수,남성연령대_60_이상_수요일시간대_4_생활인구_수,남성연령대_60_이상_수요일시간대_5_생활인구_수,남성연령대_60_이상_수요일시간대_6_생활인구_수,남성연령대_60_이상_목요일시간대_1_생활인구_수,남성연령대_60_이상_목요일시간대_2_생활인구_수,남성연령대_60_이상_목요일시간대_3_생활인구_수,남성연령대_60_이상_목요일시간대_4_생활인구_수,남성연령대_60_이상_목요일시간대_5_생활인구_수,남성연령대_60_이상_목요일시간대_6_생활인구_수,남성연령대_60_이상_금요일시간대_1_생활인구_수,남성연령대_60_이상_금요일시간대_2_생활인구_수,남성연령대_60_이상_금요일시간대_3_생활인구_수,남성연령대_60_이상_금요일시간대_4_생활인구_수,남성연령대_60_이상_금요일시간대_5_생활인구_수,남성연령대_60_이상_금요일시간대_6_생활인구_수,남성연령대_60_이상_토요일시간대_1_생활인구_수,남성연령대_60_이상_토요일시간대_2_생활인구_수,남성연령대_60_이상_토요일시간대_3_생활인구_수,남성연령대_60_이상_토요일시간대_4_생활인구_수,남성연령대_60_이상_토요일시간대_5_생활인구_수,남성연령대_60_이상_토요일시간대_6_생활인구_수,남성연령대_60_이상_일요일시간대_1_생활인구_수,남성연령대_60_이상_일요일시간대_2_생활인구_수,남성연령대_60_이상_일요일시간대_3_생활인구_수,남성연령대_60_이상_일요일시간대_4_생활인구_수,남성연령대_60_이상_일요일시간대_5_생활인구_수,남성연령대_60_이상_일요일시간대_6_생활인구_수,여성연령대_10_월요일시간대_1_생활인구_수,여성연령대_10_월요일시간대_2_생활인구_수,여성연령대_10_월요일시간대_3_생활인구_수,여성연령대_10_월요일시간대_4_생활인구_수,여성연령대_10_월요일시간대_5_생활인구_수,여성연령대_10_월요일시간대_6_생활인구_수,여성연령대_10_화요일시간대_1_생활인구_수,여성연령대_10_화요일시간대_2_생활인구_수,여성연령대_10_화요일시간대_3_생활인구_수,여성연령대_10_화요일시간대_4_생활인구_수,여성연령대_10_화요일시간대_5_생활인구_수,여성연령대_10_화요일시간대_6_생활인구_수,여성연령대_10_수요일시간대_1_생활인구_수,여성연령대_10_수요일시간대_2_생활인구_수,여성연령대_10_수요일시간대_3_생활인구_수,여성연령대_10_수요일시간대_4_생활인구_수,여성연령대_10_수요일시간대_5_생활인구_수,여성연령대_10_수요일시간대_6_생활인구_수,여성연령대_10_목요일시간대_1_생활인구_수,여성연령대_10_목요일시간대_2_생활인구_수,여성연령대_10_목요일시간대_3_생활인구_수,여성연령대_10_목요일시간대_4_생활인구_수,여성연령대_10_목요일시간대_5_생활인구_수,여성연령대_10_목요일시간대_6_생활인구_수,여성연령대_10_금요일시간대_1_생활인구_수,여성연령대_10_금요일시간대_2_생활인구_수,여성연령대_10_금요일시간대_3_생활인구_수,여성연령대_10_금요일시간대_4_생활인구_수,여성연령대_10_금요일시간대_5_생활인구_수,여성연령대_10_금요일시간대_6_생활인구_수,여성연령대_10_토요일시간대_1_생활인구_수,여성연령대_10_토요일시간대_2_생활인구_수,여성연령대_10_토요일시간대_3_생활인구_수,여성연령대_10_토요일시간대_4_생활인구_수,여성연령대_10_토요일시간대_5_생활인구_수,여성연령대_10_토요일시간대_6_생활인구_수,여성연령대_10_일요일시간대_1_생활인구_수,여성연령대_10_일요일시간대_2_생활인구_수,여성연령대_10_일요일시간대_3_생활인구_수,여성연령대_10_일요일시간대_4_생활인구_수,여성연령대_10_일요일시간대_5_생활인구_수,여성연령대_10_일요일시간대_6_생활인구_수,여성연령대_20_월요일시간대_1_생활인구_수,여성연령대_20_월요일시간대_2_생활인구_수,여성연령대_20_월요일시간대_3_생활인구_수,여성연령대_20_월요일시간대_4_생활인구_수,여성연령대_20_월요일시간대_5_생활인구_수,여성연령대_20_월요일시간대_6_생활인구_수,여성연령대_20_화요일시간대_1_생활인구_수,여성연령대_20_화요일시간대_2_생활인구_수,여성연령대_20_화요일시간대_3_생활인구_수,여성연령대_20_화요일시간대_4_생활인구_수,여성연령대_20_화요일시간대_5_생활인구_수,여성연령대_20_화요일시간대_6_생활인구_수,여성연령대_20_수요일시간대_1_생활인구_수,여성연령대_20_수요일시간대_2_생활인구_수,여성연령대_20_수요일시간대_3_생활인구_수,여성연령대_20_수요일시간대_4_생활인구_수,여성연령대_20_수요일시간대_5_생활인구_수,여성연령대_20_수요일시간대_6_생활인구_수,여성연령대_20_목요일시간대_1_생활인구_수,여성연령대_20_목요일시간대_2_생활인구_수,여성연령대_20_목요일시간대_3_생활인구_수,여성연령대_20_목요일시간대_4_생활인구_수,여성연령대_20_목요일시간대_5_생활인구_수,여성연령대_20_목요일시간대_6_생활인구_수,여성연령대_20_금요일시간대_1_생활인구_수,여성연령대_20_금요일시간대_2_생활인구_수,여성연령대_20_금요일시간대_3_생활인구_수,여성연령대_20_금요일시간대_4_생활인구_수,여성연령대_20_금요일시간대_5_생활인구_수,여성연령대_20_금요일시간대_6_생활인구_수,여성연령대_20_토요일시간대_1_생활인구_수,여성연령대_20_토요일시간대_2_생활인구_수,여성연령대_20_토요일시간대_3_생활인구_수,여성연령대_20_토요일시간대_4_생활인구_수,여성연령대_20_토요일시간대_5_생활인구_수,여성연령대_20_토요일시간대_6_생활인구_수,여성연령대_20_일요일시간대_1_생활인구_수,여성연령대_20_일요일시간대_2_생활인구_수,여성연령대_20_일요일시간대_3_생활인구_수,여성연령대_20_일요일시간대_4_생활인구_수,여성연령대_20_일요일시간대_5_생활인구_수,여성연령대_20_일요일시간대_6_생활인구_수,여성연령대_30_월요일시간대_1_생활인구_수,여성연령대_30_월요일시간대_2_생활인구_수,여성연령대_30_월요일시간대_3_생활인구_수,여성연령대_30_월요일시간대_4_생활인구_수,여성연령대_30_월요일시간대_5_생활인구_수,여성연령대_30_월요일시간대_6_생활인구_수,여성연령대_30_화요일시간대_1_생활인구_수,여성연령대_30_화요일시간대_2_생활인구_수,여성연령대_30_화요일시간대_3_생활인구_수,여성연령대_30_화요일시간대_4_생활인구_수,여성연령대_30_화요일시간대_5_생활인구_수,여성연령대_30_화요일시간대_6_생활인구_수,여성연령대_30_수요일시간대_1_생활인구_수,여성연령대_30_수요일시간대_2_생활인구_수,여성연령대_30_수요일시간대_3_생활인구_수,여성연령대_30_수요일시간대_4_생활인구_수,여성연령대_30_수요일시간대_5_생활인구_수,여성연령대_30_수요일시간대_6_생활인구_수,여성연령대_30_목요일시간대_1_생활인구_수,여성연령대_30_목요일시간대_2_생활인구_수,여성연령대_30_목요일시간대_3_생활인구_수,여성연령대_30_목요일시간대_4_생활인구_수,여성연령대_30_목요일시간대_5_생활인구_수,여성연령대_30_목요일시간대_6_생활인구_수,여성연령대_30_금요일시간대_1_생활인구_수,여성연령대_30_금요일시간대_2_생활인구_수,여성연령대_30_금요일시간대_3_생활인구_수,여성연령대_30_금요일시간대_4_생활인구_수,여성연령대_30_금요일시간대_5_생활인구_수,여성연령대_30_금요일시간대_6_생활인구_수,여성연령대_30_토요일시간대_1_생활인구_수,여성연령대_30_토요일시간대_2_생활인구_수,여성연령대_30_토요일시간대_3_생활인구_수,여성연령대_30_토요일시간대_4_생활인구_수,여성연령대_30_토요일시간대_5_생활인구_수,여성연령대_30_토요일시간대_6_생활인구_수,여성연령대_30_일요일시간대_1_생활인구_수,여성연령대_30_일요일시간대_2_생활인구_수,여성연령대_30_일요일시간대_3_생활인구_수,여성연령대_30_일요일시간대_4_생활인구_수,여성연령대_30_일요일시간대_5_생활인구_수,여성연령대_30_일요일시간대_6_생활인구_수,여성연령대_40_월요일시간대_1_생활인구_수,여성연령대_40_월요일시간대_2_생활인구_수,여성연령대_40_월요일시간대_3_생활인구_수,여성연령대_40_월요일시간대_4_생활인구_수,여성연령대_40_월요일시간대_5_생활인구_수,여성연령대_40_월요일시간대_6_생활인구_수,여성연령대_40_화요일시간대_1_생활인구_수,여성연령대_40_화요일시간대_2_생활인구_수,여성연령대_40_화요일시간대_3_생활인구_수,여성연령대_40_화요일시간대_4_생활인구_수,여성연령대_40_화요일시간대_5_생활인구_수,여성연령대_40_화요일시간대_6_생활인구_수,여성연령대_40_수요일시간대_1_생활인구_수,여성연령대_40_수요일시간대_2_생활인구_수,여성연령대_40_수요일시간대_3_생활인구_수,여성연령대_40_수요일시간대_4_생활인구_수,여성연령대_40_수요일시간대_5_생활인구_수,여성연령대_40_수요일시간대_6_생활인구_수,여성연령대_40_목요일시간대_1_생활인구_수,여성연령대_40_목요일시간대_2_생활인구_수,여성연령대_40_목요일시간대_3_생활인구_수,여성연령대_40_목요일시간대_4_생활인구_수,여성연령대_40_목요일시간대_5_생활인구_수,여성연령대_40_목요일시간대_6_생활인구_수,여성연령대_40_금요일시간대_1_생활인구_수,여성연령대_40_금요일시간대_2_생활인구_수,여성연령대_40_금요일시간대_3_생활인구_수,여성연령대_40_금요일시간대_4_생활인구_수,여성연령대_40_금요일시간대_5_생활인구_수,여성연령대_40_금요일시간대_6_생활인구_수,여성연령대_40_토요일시간대_1_생활인구_수,여성연령대_40_토요일시간대_2_생활인구_수,여성연령대_40_토요일시간대_3_생활인구_수,여성연령대_40_토요일시간대_4_생활인구_수,여성연령대_40_토요일시간대_5_생활인구_수,여성연령대_40_토요일시간대_6_생활인구_수,여성연령대_40_일요일시간대_1_생활인구_수,여성연령대_40_일요일시간대_2_생활인구_수,여성연령대_40_일요일시간대_3_생활인구_수,여성연령대_40_일요일시간대_4_생활인구_수,여성연령대_40_일요일시간대_5_생활인구_수,여성연령대_40_일요일시간대_6_생활인구_수,여성연령대_50_월요일시간대_1_생활인구_수,여성연령대_50_월요일시간대_2_생활인구_수,여성연령대_50_월요일시간대_3_생활인구_수,여성연령대_50_월요일시간대_4_생활인구_수,여성연령대_50_월요일시간대_5_생활인구_수,여성연령대_50_월요일시간대_6_생활인구_수,여성연령대_50_화요일시간대_1_생활인구_수,여성연령대_50_화요일시간대_2_생활인구_수,여성연령대_50_화요일시간대_3_생활인구_수,여성연령대_50_화요일시간대_4_생활인구_수,여성연령대_50_화요일시간대_5_생활인구_수,여성연령대_50_화요일시간대_6_생활인구_수,여성연령대_50_수요일시간대_1_생활인구_수,여성연령대_50_수요일시간대_2_생활인구_수,여성연령대_50_수요일시간대_3_생활인구_수,여성연령대_50_수요일시간대_4_생활인구_수,여성연령대_50_수요일시간대_5_생활인구_수,여성연령대_50_수요일시간대_6_생활인구_수,여성연령대_50_목요일시간대_1_생활인구_수,여성연령대_50_목요일시간대_2_생활인구_수,여성연령대_50_목요일시간대_3_생활인구_수,여성연령대_50_목요일시간대_4_생활인구_수,여성연령대_50_목요일시간대_5_생활인구_수,여성연령대_50_목요일시간대_6_생활인구_수,여성연령대_50_금요일시간대_1_생활인구_수,여성연령대_50_금요일시간대_2_생활인구_수,여성연령대_50_금요일시간대_3_생활인구_수,여성연령대_50_금요일시간대_4_생활인구_수,여성연령대_50_금요일시간대_5_생활인구_수,여성연령대_50_금요일시간대_6_생활인구_수,여성연령대_50_토요일시간대_1_생활인구_수,여성연령대_50_토요일시간대_2_생활인구_수,여성연령대_50_토요일시간대_3_생활인구_수,여성연령대_50_토요일시간대_4_생활인구_수,여성연령대_50_토요일시간대_5_생활인구_수,여성연령대_50_토요일시간대_6_생활인구_수,여성연령대_50_일요일시간대_1_생활인구_수,여성연령대_50_일요일시간대_2_생활인구_수,여성연령대_50_일요일시간대_3_생활인구_수,여성연령대_50_일요일시간대_4_생활인구_수,여성연령대_50_일요일시간대_5_생활인구_수,여성연령대_50_일요일시간대_6_생활인구_수,여성연령대_60_이상_월요일시간대_1_생활인구_수,여성연령대_60_이상_월요일시간대_2_생활인구_수,여성연령대_60_이상_월요일시간대_3_생활인구_수,여성연령대_60_이상_월요일시간대_4_생활인구_수,여성연령대_60_이상_월요일시간대_5_생활인구_수,여성연령대_60_이상_월요일시간대_6_생활인구_수,여성연령대_60_이상_화요일시간대_1_생활인구_수,여성연령대_60_이상_화요일시간대_2_생활인구_수,여성연령대_60_이상_화요일시간대_3_생활인구_수,여성연령대_60_이상_화요일시간대_4_생활인구_수,여성연령대_60_이상_화요일시간대_5_생활인구_수,여성연령대_60_이상_화요일시간대_6_생활인구_수,여성연령대_60_이상_수요일시간대_1_생활인구_수,여성연령대_60_이상_수요일시간대_2_생활인구_수,여성연령대_60_이상_수요일시간대_3_생활인구_수,여성연령대_60_이상_수요일시간대_4_생활인구_수,여성연령대_60_이상_수요일시간대_5_생활인구_수,여성연령대_60_이상_수요일시간대_6_생활인구_수,여성연령대_60_이상_목요일시간대_1_생활인구_수,여성연령대_60_이상_목요일시간대_2_생활인구_수,여성연령대_60_이상_목요일시간대_3_생활인구_수,여성연령대_60_이상_목요일시간대_4_생활인구_수,여성연령대_60_이상_목요일시간대_5_생활인구_수,여성연령대_60_이상_목요일시간대_6_생활인구_수,여성연령대_60_이상_금요일시간대_1_생활인구_수,여성연령대_60_이상_금요일시간대_2_생활인구_수,여성연령대_60_이상_금요일시간대_3_생활인구_수,여성연령대_60_이상_금요일시간대_4_생활인구_수,여성연령대_60_이상_금요일시간대_5_생활인구_수,여성연령대_60_이상_금요일시간대_6_생활인구_수,여성연령대_60_이상_토요일시간대_1_생활인구_수,여성연령대_60_이상_토요일시간대_2_생활인구_수,여성연령대_60_이상_토요일시간대_3_생활인구_수,여성연령대_60_이상_토요일시간대_4_생활인구_수,여성연령대_60_이상_토요일시간대_5_생활인구_수,여성연령대_60_이상_토요일시간대_6_생활인구_수,여성연령대_60_이상_일요일시간대_1_생활인구_수,여성연령대_60_이상_일요일시간대_2_생활인구_수,여성연령대_60_이상_일요일시간대_3_생활인구_수,여성연령대_60_이상_일요일시간대_4_생활인구_수,여성연령대_60_이상_일요일시간대_5_생활인구_수,여성연령대_60_이상_일요일시간대_6_생활인구_수
0,2021,1,A,골목상권,1000001,계동길,282796,142207,140590,34007,40035,51839,60856,43971,52088,51175,63043,46872,47847,46527,27332,42432,44311,43579,43185,41685,34576,33028,498,649,479,398,389,277,541,742,453,425,423,286,505,711,489,439,403,274,505,728,463,421,429,292,514,706,485,453,386,251,464,411,284,265,315,213,482,353,265,255,274,243,500,569,429,454,464,281,497,576,486,488,499,261,481,560,451,487,483,260,493,550,458,489,471,257,484,528,444,498,484,281,495,444,378,515,519,302,498,460,390,506,476,263,465,1212,919,941,730,289,499,1308,990,1013,783,298,501,1242,969,990,754,289,488,1240,946,954,775,295,485,1165,874,849,624,273,465,451,421,481,500,259,469,438,380,414,422,250,775,1395,962,974,829,401,732,1494,1038,1072,869,397,739,1419,1002,1028,840,386,722,1405,982,995,840,389,716,1323,920,907,724,372,708,681,465,455,518,354,693,638,443,440,503,385,553,947,641,626,541,298,570,983,672,654,570,300,545,963,642,623,558,305,559,935,659,641,549,296,551,899,609,585,513,308,553,509,390,403,440,296,557,487,341,353,425,296,716,680,448,434,486,343,715,698,486,450,462,345,718,687,464,446,477,342,724,663,443,443,463,343,719,669,431,440,486,344,706,614,398,400,436,342,706,581,377,362,436,343,426,536,362,365,437,277,474,556,374,362,428,243,388,555,392,384,410,259,410,550,379,363,397,269,460,564,391,389,399,258,431,375,307,333,385,243,424,380,304,319,365,238,441,590,527,566,529,245,377,627,569,641,612,237,429,614,576,645,624,251,383,596,553,634,618,246,406,585,528,637,619,262,415,412,500,772,696,271,451,439,475,690,605,242,489,813,687,693,581,296,490,874,761,770,623,290,480,847,768,755,633,291,489,849,733,740,612,281,474,754,686,692,572,288,478,436,466,602,561,283,491,424,413,493,484,284,842,913,661,664,656,426,868,936,694,702,652,412,865,939,698,691,631,407,836,918,672,678,648,426,829,877,647,655,625,415,827,707,513,546,563,400,790,689,480,525,595,411,684,635,430,426,483,332,683,672,468,467,488,336,684,661,474,460,484,333,682,649,463,456,490,332,678,625,435,437,477,331,667,560,419,420,480,333,657,560,358,365,423,331,989,957,630,571,740,537,1012,983,675,608,750,524,1005,972,656,583,726,535,1005,971,682,608,736,528,993,970,643,566,697,522,984,903,603,585,730,519,981,858,547,524,694,519,NaN
1,2021,1,A,골목상권,1000002,난계로27길,320864,164461,156403,16361,61774,60579,51914,52050,78184,74165,66430,49959,50951,46326,33033,45027,45415,45956,45149,44570,46564,48182,259,213,128,125,152,114,256,228,156,142,145,113,221,238,170,144,155,107,264,239,152,136,153,106,260,232,158,154,150,116,268,205,142,165,168,122,285,232,155,180,174,127,934,655,378,377,472,409,929,659,369,402,473,417,917,661,366,372,458,405,883,643,365,395,445,380,895,636,365,372,461,410,914,747,416,418,475,435,965,744,428,417,459,425,1207,940,556,560,672,557,1231,954,563,565,656,552,1225,943,555,561,654,549,1213,963,578,559,640,526,1160,923,547,559,632,525,1164,961,561,564,596,536,1250,1023,578,580,647,548,866,897,664,642,634,418,873,897,660,651,647,425,865,901,700,670,642,409,864,882,654,642,621,423,869,864,635,628,600,390,863,818,609,613,550,395,893,845,614,631,564,402,800,861,711,700,677,404,824,881,702,720,703,387,827,877,737,760,712,398,804,858,727,754,689,393,805,844,726,756,698,395,812,912,880,956,664,395,832,895,1023,1051,628,377,944,1023,1058,1184,839,464,945,1044,1095,1221,846,464,954,1060,1175,1338,906,490,979,1058,1137,1276,858,453,935,1020,1154,1312,853,468,946,1175,1819,2004,943,477,929,1219,2211,2411,939,470,322,266,155,143,168,156,318,289,172,165,174,133,346,300,166,148,184,150,331,270,173,152,167,144,351,293,156,158,170,144,355,298,173,169,200,142,342,296,176,200,197,142,1807,1177,590,570,732,717,1803,1169,581,552,720,712,1814,1183,586,568,717,693,1785,1166,574,553,721,703,1733,1146,571,558,692,682,1709,1290,629,588,713,716,1771,1336,652,600,723,733,1106,909,566,562,640,490,1123,899,558,558,602,481,1176,929,558,548,633,492,1147,896,543,558,604,478,1125,892,523,502,568,481,1106,899,498,469,554,474,1142,905,489,481,588,493,733,775,590,585,540,322,772,778,609,594,532,330,765,791,581,589,528,324,766,751,586,594,521,319,736,746,567,551,497,316,697,612,430,466,416,318,739,639,424,430,412,317,525,683,598,580,522,259,531,692,608,610,547,267,530,678,599,592,534,257,528,681,600,586,520,253,533,658,590,580,513,260,539,582,529,538,447,253,535,528,495,512,390,228,1064,1017,774,741,684,464,1056,1030,752,742,691,473,1062,1058,805,768,712,467,1048,1015,758,762,715,471,1071,1014,772,755,699,463,1059,1018,900,924,697,469,1036,1004,920,983,695,476,NaN
2,2021,1,A,골목상권,1000003,돈화문로11가길,162400,90505,71895,9073,32314,32489,31239,25484,31800,23723,30757,30038,32446,32562,12871,23640,25007,25436,24577,24013,21348,18378,184,145,107,105,126,79,174,146,102,101,124,80,183,149,103,104,131,74,177,139,99,98,125,80,194,155,97,97,140,87,188,155,130,160,179,100,211,148,105,127,131,70,331,351,307,344,408,178,326,350,309,344,446,189,342,348,318,357,466,189,350,355,314,349,462,194,331,341,300,357,543,247,387,325,319,487,775,283,445,371,315,422,578,194,294,679,616,603,521,181,327,750,670,657,576,190,328,735,648,642,581,197,328,697,618,619,569,197,325,649,590,575,546,215,322,298,291,386,568,231,361,299,255,308,370,165,381,697,626,625,565,229,435,748,668,650,603,243,457,748,661,642,617,248,456,724,635,615,599,239,440,669,569,562,529,235,405,371,294,324,393,209,377,342,249,268,305,190,271,499,467,472,435,161,301,543,513,499,461,172,308,537,510,508,470,176,316,514,488,474,451,169,307,486,435,429,414,169,297,296,265,299,317,155,273,260,207,230,244,139,396,489,499,488,419,197,410,506,527,522,427,203,423,511,531,524,436,195,404,481,498,504,426,201,394,456,461,463,416,197,385,387,350,379,375,200,382,337,258,272,288,184,41,67,76,116,110,29,32,67,75,107,131,34,35,63,85,116,136,31,28,63,77,113,132,36,42,74,87,142,154,45,58,57,117,204,198,50,61,59,117,193,167,37,236,373,429,543,559,144,223,382,440,550,584,152,229,377,447,571,633,152,221,354,430,557,632,160,229,346,415,549,709,201,272,258,417,769,983,238,344,312,390,650,749,161,208,409,448,441,354,113,219,445,469,469,381,120,222,436,477,479,414,126,215,420,447,459,401,126,223,392,437,451,415,139,234,208,274,389,444,152,261,229,241,314,297,110,216,338,383,375,289,106,219,373,419,411,326,111,225,362,420,408,331,119,227,346,394,388,326,114,227,321,367,367,325,120,222,208,240,284,273,110,222,185,191,216,195,99,204,286,318,327,276,109,228,309,349,351,298,113,230,322,361,371,319,118,227,297,345,345,315,118,219,285,308,322,294,119,214,211,252,289,267,116,221,196,187,207,202,101,432,463,417,388,347,197,435,484,444,404,358,205,462,498,467,429,368,198,445,466,433,401,355,203,444,460,411,390,354,204,427,405,343,348,329,209,413,369,268,263,280,188,NaN

In [ ]:
df7 = pd.read_csv('./7.직장인구.csv', encoding='cp949')

C:\Users\82103\AppData\Local\Temp\ipykernel_5348\2346517672.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df7 = pd.read_csv('./7.직장인구.csv', encoding='cp949')

In [ ]:
df7.head(10).T

,0,1,2,3,4,5,6,7,8,9
기준_년월_코드,2021,2021,2021,2021,2021,2021,2021,2021,2021,2021
기준_분기_코드,1,1,1,1,1,1,1,1,1,1
상권_구분_코드,A,A,R,A,A,A,A,A,A,A
상권_구분_코드_명,골목상권,골목상권,전통시장,골목상권,골목상권,골목상권,골목상권,골목상권,골목상권,골목상권
상권_코드,1000007,1000756,1001278,1000058,1000059,1000060,1000061,1000062,1000063,1000064
상권_코드_명,북촌로5길,사당로8길,남평화시장,백범로90길,서빙고로71길,소월로20길,신흥로20길,우사단로10길,우사단로14길,우사단로4길
총_직장_인구_수,503,131,5,535,432,151,178,570,1987,308
남성_직장_인구_수,419,70,3,288,265,76,118,508,984,143
여성_직장_인구_수,84,61,2,247,167,75,60,62,1003,165
연령대_10_직장_인구_수,0,0,0,0,1,0,0,1,9,0
연령대_20_직장_인구_수,31,16,0,62,40,28,26,64,439,72
연령대_30_직장_인구_수,177,19,4,133,104,48,36,165,854,52
연령대_40_직장_인구_수,156,41,0,161,117,37,57,163,523,54
연령대_50_직장_인구_수,102,37,0,112,81,30,37,156,137,83
연령대_60_이상_직장_인구_수,37,18,1,67,89,8,22,21,25,47
남성연령대_10_직장_인구_수,0,0,0,0,0,0,0,0,2,0
남성연령대_20_직장_인구_수,19,2,0,28,14,8,11,41,107,11
남성연령대_30_직장_인구_수,150,9,2,71,49,24,27,143,386,31
남성연령대_40_직장_인구_수,133,24,0,89,58,17,40,156,353,32
남성연령대_50_직장_인구_수,88,22,0,57,64,20,27,151,120,42
남성연령대_60_이상_직장_인구_수,29,13,1,43,80,7,13,17,16,27
여성연령대_10_직장_인구_수,0,0,0,0,1,0,0,1,7,0
여성연령대_20_직장_인구_수,12,14,0,34,26,20,15,23,332,61
여성연령대_30_직장_인구_수,27,10,2,62,55,24,9,22,468,21
여성연령대_40_직장_인구_수,23,17,0,72,59,20,17,7,170,22
여성연령대_50_직장_인구_수,14,15,0,55,17,10,10,5,17,41
여성연령대_60_이상_직장_인구_수,8,5,0,24,9,1,9,4,9,20

In [59]:
df8 = pd.read_csv('./8.상주인구.csv', encoding='cp949')

C:\Users\82103\AppData\Local\Temp\ipykernel_5348\417379837.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df8 = pd.read_csv('./8.상주인구.csv', encoding='cp949')

In [60]:
df8.head(5).T

                          0        1        2        3        4
기준_년_코드                2021     2021     2021     2021     2021
기준_분기_코드                  1        1        1        1        1
상권_구분_코드                  A        A        A        A        R
상권_구분_코드_명             골목상권     골목상권     골목상권     골목상권     전통시장
상권 코드               1000002  1000011  1000010  1000012  1001451
총 상주인구 수                941      899      946     2571        8
남성 상주인구 수               406      484      454     1139        5
여성 상주인구 수               535      415      492     1432        3
연령대 10 상주인구 수            18       75       94      432        0
연령대 20 상주인구 수           437      136      341      288        3
연령대 30 상주인구 수           252      102      137      399        1
연령대 40 상주인구 수            88      109      106      506        0
연령대 50 상주인구 수            69      191      104      412        3
연령대 60 이상 상주인구 수         77      286      164      534        1
남성연령대 10 상주인구 수          10       42       50      201        0
남성연령대 20 상주인구 수         109       77      165      131        2
남성연령대 30 상주인구 수         125       58       71      181        1
남성연령대 40 상주인구 수          56       62       49      213        0
남성연령대 50 상주인구 수          52      109       50      193        1
남성연령대 60 이상 상주인구 수       54      136       69      220        1
여성연령대 10 상주인구 수           8       33       44      231        0
여성연령대 20 상주인구 수         328       59      176      157        1
여성연령대 30 상주인구 수         127       44       66      218        0
여성연령대 40 상주인구 수          32       47       57      293        0
여성연령대 50 상주인구 수          17       82       54      219        2
여성연령대 60 이상 상주인구 수       23      150       95      314        0
총 가구 수                  854      520      603     1095        3
아파트 가구 수                  0        0        0        0        0
비 아파트 가구 수              854      520      603     1095        3
상권 코드 명              난계로27길     숭인동길   성균관로5길      옥인길     사당시장

In [51]:
df9 = pd.read_csv('./9.아파트.csv', encoding='cp949')

In [52]:
df9.head(5).T

                                0          1          2          3          4
기준_년_코드                      2021       2021       2021       2021       2021
기준_분기_코드                        4          3          2          1          4
상권_구분_코드                        R          R          R          R          R
상권_구분_코드_명                   전통시장       전통시장       전통시장       전통시장       전통시장
상권_코드                     2130326    2130326    2130326    2130326    2130325
상권_코드_명                 고덕 골목형상점가  고덕 골목형상점가  고덕 골목형상점가  고덕 골목형상점가     명일전통시장
아파트_단지_수                        1          1          1          1          5
아파트_면적_66_제곱미터_미만_세대_수        6.0        6.0        6.0        6.0      203.0
아파트_면적_66_제곱미터_세대_수           NaN        NaN        NaN        NaN      372.0
아파트_면적_99_제곱미터_세대_수           NaN        NaN        NaN        NaN        NaN
아파트_면적_132_제곱미터_세대_수          NaN        NaN        NaN        NaN        NaN
아파트_면적_165_제곱미터_세대_수          NaN        NaN        NaN        NaN        NaN
아파트_가격_1_억_미만_세대_수            NaN        NaN        NaN        NaN        3.0
아파트_가격_1_억_세대_수               6.0        6.0        6.0        6.0       20.0
아파트_가격_2_억_세대_수               NaN        NaN        NaN        NaN        1.0
아파트_가격_3_억_세대_수               NaN        NaN        NaN        NaN      227.0
아파트_가격_4_억_세대_수               NaN        NaN        NaN        NaN      324.0
아파트_가격_5_억_세대_수               NaN        NaN        NaN        NaN        NaN
아파트_가격_6_억_이상_세대_수            NaN        NaN        NaN        NaN        NaN
아파트_평균_면적                      41         41         41         41         61
아파트_평균_시가               177666667  177666667  177666667  177666667  238201494